workspace:
  base: /go
  path: src/github.com/flyxl/gin-example

pipeline:
  build:
    image: golang:1.11.0-alpine3.8
    commands:
      - go get
      - go test
      - go build -ldflags "-s -w" -o bin/eospark_openapi